name: Build C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
<<<<<<< HEAD
          sudo apt-get install -y -f build-essential g++ cmake
=======
          sudo apt-get install -y build-essential g++ cmake

>>>>>>> 31202bd (C++ build)
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: g++ main.cpp -std=c++17 -o firstIO